### ISSUE TITLE
undefined reference to `virtual thunk to veins::TraCIScenarioManagerLaunchd::finish()'

### ISSUE THREAD

**Issue by a-huk** [sommer/veins#212]
When using the veins_inet project on windows omnetpp, I get this error. On linux it is fine.

**Comment by sommer** [comment]
Using The INET Framework as a basis of other projects works reliably on Linux, but (as of INET 4.2.3) less so on Windows. If you use INET 4.2.4 and the current master version of Veins (which adds support for this version) things should work on OMNeT++ 5.6.2

**Comment by a-huk** [comment]
Cheers, will try it.

**Comment by sommer** [comment]
I am assuming using INET 4.2.4 and b14411eb9aaff0a475899c925015be1f844af505 on OMNeT++ 5.6.2 fixed this. Please add a comment here if it did not.

**Comment by shriyaBhat1** [comment]
undefined reference to `virtual thunk to veins::TraCIScenarioManagerLaunchd::finish()'

Hello Sir Have you resolved this error?
Even I'm also getting the same problem so help me.

**Comment by Thilaga22** [comment]
I am using Veins current version , OMNEST and inet-4.2.5-e0c1741924 version. 
I am still getting the same error. 
Any help on this?

**Comment by imssuthar** [comment]
> undefined reference to `virtual thunk to veins::TraCIScenarioManagerLaunchd::finish()'
> 
> Hello Sir Have you resolved this error? Even I'm also getting the same problem so help me.

@shriyaBhat1  did you get solution for this?

**Comment by zenobertesina** [comment]
I'm using the 5.6.2 version of Omnet++ and when I try to run the veins_inet subproject on windows 10 I get the following error. I have tried multiple versions of inet (4.2.1, 4.2.2, 4.2.5) with veins 5.1, but the error is still there. I also tried to use the inet-master and veins-master versions, because they work on the on the computer of a collegue, but the situation still doesn't change. I also try to use different versions  of SUMO (1.8.0, 1.10.0). The interesting thing is that Inet and Veins work well separately, but when I try to connect them the simulation crashes. 
Do you have any solution for this problem? 

Thanks,
Zeno Bertesina 

![error-thunk](https://user-images.githubusercontent.com/95923518/145587387-09b3478a-0876-47f3-a620-00dcd26ba79c.png)

**Comment by sommer** [comment]
The patch mentioned in the issue is now merged into Veins 5.2 (see https://github.com/sommer/veins/releases/tag/veins-5.2)

**Comment by sommer** [comment]
> I have tried multiple versions of inet (4.2.1, 4.2.2, 4.2.5) [and] different versions of SUMO (1.8.0, 1.10.0). The interesting thing is that Inet and Veins work well separately, but when I try to connect them the simulation crashes.

If you can consider switching to Veins 5.2, there is a table of tested combinations of OMNeT++ + INET + SUMO + Veins available on http://veins.car2x.org/download/.

**Comment by zenobertesina** [comment]
I have followed your suggestion (Veins 5.2, Inet 4.2.5, Sumo 1.10.0), but the problem is still there.

**Comment by sommer** [comment]
I can only recommend giving Instant Veins a try. This should work out of the box.

**Comment by nawroooz** [comment]
I have the same problem and I tried to import inet-4.2.4 but still facing the same issue
please can you help me?

**Comment by nawroooz** [comment]
Actually I just switched to the version of omnet which is build in on virtual box since it comes with whole package of frameworks together without need for individual installation.
